# Generated by Django 4.0.4 on 2022-07-02 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0005_alter_publicacion_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='main_image',
            field=models.ImageField(blank=True, default='post_image/post-image-default-2.png', null=True, upload_to='post_image'),
        ),
    ]
